### ISSUE TITLE
gametest2 version-6e0792f2dcac4abe

### ISSUE THREAD

**Issue by InterSyncz** [ohoshk/DeployHistory-Recreations#1]
Found at: https://web.archive.org/web/20140522204217/http://setup.gametest2.robloxlabs.com/versionQTStudio
`New Studio version-6e0792f2dcac4abe at 5/22/2014 2:01:44 AM, file version: 0, 152, 0, 46877...Done!`

**Comment by ohoshk** [comment]
forgot to close
