### ISSUE TITLE
Propose to add new versions to all sitetest deploys. ("hidden" versions)

### ISSUE THREAD

**Issue by Robox-Corporation** [ohoshk/DeployHistory-Recreations#10]
Recently, Roblox now "hides" versions from DeployHistory on sitetests. They still left /version and /versionQTStudio open though. An example is how you'll see "version-hidden" on new versions. I have made a tracker to actually recreate the new deployhistory, by taking the version from /version or /versionQTStudio whenever it changes, and matching it up with the latest line from DeployHistory corresponding to what kind of EXE it is, (WindowsPlayer or Studio). So far I've had good results.

**Comment by genocydr** [comment]
Does this still work?

**Comment by Robox-Corporation** [comment]
no
